### ISSUE TITLE
Couple of lint errors being thrown

### ISSUE THREAD

**Issue by drgrigg** [vr8hub/victor-hugo_notre-dame-de-paris_isabel-f-hapgood#1]
Could you address these?

Manual Review: chapter-10-1.xhtml Title "Gringoire Has Many Good Ideas in Succession.⁠—Rue des Bernardins" not correctly titlecased. Expected: Gringoire Has Many Good Ideas in Succession.⁠—Rue Des Bernardins
Manual Review: endnotes.xhtml Roman numeral followed by a period. When in mid-sentence Roman numerals must not be followed by a period.
	<span epub:type="z3998:roman">III</span>. f

**Comment by vr8hub** [comment]
Right, I left those because they're both valid, I believe. I could be wrong, of course. :)

Rue des Barnadins is the correct punctuation for the street/avenue; the des isn't capitalized (it appears in the chapter, it can be seen there as well).
In the case of roman numeral, it looked to me like that period was part of the nomenclature for the reference.
    Histoire Gallicane, liv. II. Periode III. fo. 130, p. 1.
Lots of periods there, I thought they were all for the same reason. But I'll be glad to get rid of it if you think otherwise; I am the opposite of an expert on endnote references. :)

**Comment by drgrigg** [comment]
That’s all fine. That’s why lint marks them as for manual review, rather than as errors. I should have looked more closely myself.
