### ISSUE TITLE
Unsemantic <i> tags in endnotes

### ISSUE THREAD

**Issue by drgrigg** [vr8hub/victor-hugo_notre-dame-de-paris_isabel-f-hapgood#2]
A search for plain `<i>` yields several instances in the endnotes. Most could be given xml:lang="fr"  or ="la" tags. There's also a reference to a book title (se:name.publication.book) and a couple that should be `<em>` instead. Also, there's a roman numeral `liv` which should have <span epub:type="z3998:roman"> around it.

**Comment by vr8hub** [comment]
I believe I've fixed all of these with what should be appropriate for their usage. I will point out Note 23 that has "(_Note to the fifth edition_.)" at the end. I changed them to <em> there, but that seems iffy to me; if you think it should be something else, let me know.

**Comment by vr8hub** [comment]
Oops. I didn't quote my em's. What I was trying to say was that I swapped out i for em in that case, but I wasn't sure about it.

**Comment by vr8hub** [comment]
Sorry, I just realized I didn't address the "liv." I don't think those are roman numerals, I believe it's the abbreviation for "livre", i.e. "book", which is why I left them alone. They're lower case, which none of the other roman numerals were in the transcription, and a digital copy of the book showed the sections labeled as "Livre IV," "Livre V," etc. So that was my guess, that it was saying "livre II. Periode III. fo. 130, p. 1." (As I mentioned in the other issue, that's also why I left the periods after the numerals there; it looked to me like they were using them as true punctuation.)

**Comment by drgrigg** [comment]
Ok. I’m right in the midst of producing The Lives of the Twelve Caesars by Suetonius, so everything is beginning to look like a Roman numeral to me!!

**Comment by drgrigg** [comment]
I think you are right about Note 23, leave it as simple `<i>` tags. It’s not an inflexible rule about semantic tagging, just we like to avoid bare i tags wherever possible.
